train:
  drop_last: True

  accumulation_steps: 4

  batch_size: 256 # 256

  num_epochs: 10 # 100

  optimizer:
    name: 'SGD' # SGD
    learning_rate: 0.1 # 0.1
    weight_decay: 0.0001 # 0.0001
    momentum: 0.9 # 0.9
